# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_oa2a')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_oa2a')
    _oa2a = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_oa2a', [dirname(__file__)])
        except ImportError:
            import _oa2a
            return _oa2a
        try:
            _mod = imp.load_module('_oa2a', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _oa2a = swig_import_helper()
    del swig_import_helper
else:
    import _oa2a
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class test(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, test, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, test, name)
    __repr__ = _swig_repr

    def __init__(self, str):
        this = _oa2a.new_test(str)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def getlen(self):
        return _oa2a.test_getlen(self)
    __swig_destroy__ = _oa2a.delete_test
    __del__ = lambda self: None
test_swigregister = _oa2a.test_swigregister
test_swigregister(test)

class oaString_w(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, oaString_w, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, oaString_w, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _oa2a.delete_oaString_w
    __del__ = lambda self: None

    def __init__(self, *args):
        this = _oa2a.new_oaString_w(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def getlen(self):
        return _oa2a.oaString_w_getlen(self)

    def setstr(self, str):
        return _oa2a.oaString_w_setstr(self, str)

    def toLower(self):
        return _oa2a.oaString_w_toLower(self)
oaString_w_swigregister = _oa2a.oaString_w_swigregister
oaString_w_swigregister(oaString_w)


def main():
    return _oa2a.main()
main = _oa2a.main
class oaMemory(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, oaMemory, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, oaMemory, name)
    __repr__ = _swig_repr
    if _newclass:
        free = staticmethod(_oa2a.oaMemory_free)
    else:
        free = _oa2a.oaMemory_free
    if _newclass:
        get = staticmethod(_oa2a.oaMemory_get)
    else:
        get = _oa2a.oaMemory_get
    if _newclass:
        resize = staticmethod(_oa2a.oaMemory_resize)
    else:
        resize = _oa2a.oaMemory_resize

    def __init__(self):
        this = _oa2a.new_oaMemory()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _oa2a.delete_oaMemory
    __del__ = lambda self: None
oaMemory_swigregister = _oa2a.oaMemory_swigregister
oaMemory_swigregister(oaMemory)

def oaMemory_free(arg2):
    return _oa2a.oaMemory_free(arg2)
oaMemory_free = _oa2a.oaMemory_free

def oaMemory_get(arg2):
    return _oa2a.oaMemory_get(arg2)
oaMemory_get = _oa2a.oaMemory_get

def oaMemory_resize(arg2, arg3):
    return _oa2a.oaMemory_resize(arg2, arg3)
oaMemory_resize = _oa2a.oaMemory_resize

class oaString(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, oaString, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, oaString, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _oa2a.delete_oaString
    __del__ = lambda self: None

    def __init__(self, *args):
        this = _oa2a.new_oaString(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def toLower(self):
        return _oa2a.oaString_toLower(self)

    def getLength(self):
        return _oa2a.oaString_getLength(self)
oaString_swigregister = _oa2a.oaString_swigregister
oaString_swigregister(oaString)

# This file is compatible with both classic and new-style classes.


